apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "enterprise-stack.fullname" . }}-api
spec:
  replicas: {{ .Values.api.replicas }}
  selector:
    matchLabels:
      app: waltid-enterprise-api
      {{- include "enterprise-stack.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: waltid-enterprise-api
        {{- include "enterprise-stack.selectorLabels" . | nindent 8 }}
      annotations:
        latest-restart: {{ now | unixEpoch | quote }}
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 10001
        seccompProfile:
          type: RuntimeDefault
      imagePullSecrets:
        - name: {{ .Values.api.image.pullSecrets }}
      containers:
      - name: waltid-enterprise-api
        image: {{ .Values.api.image.repository }}:{{ .Values.api.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: {{ .Values.api.image.imagePullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        resources:
          requests:
            cpu: "100m"
        startupProbe:
          httpGet:
            path: /livez
            port: http-api
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /livez
            port: http-api
        env:
        {{- if .Values.loggingConf }}
          - name: KLOGGING_CONFIG_PATH
            value: /config/klogging.json
        {{- end }}
        ports:
        - containerPort: 3000
          name: http-api
        volumeMounts:
          - name: waltid-enterprise-api-config
            mountPath: /config/_features.conf
            readOnly: true
            subPath: _features.conf
          - name: waltid-enterprise-api-config
            mountPath: /config/auth.conf
            readOnly: true
            subPath: auth.conf
          - name: waltid-enterprise-api-config
            mountPath: /config/database.conf
            readOnly: true
            subPath: database.conf
          - name: waltid-enterprise-api-config
            mountPath: /config/superadmin-registration.conf
            readOnly: true
            subPath: superadmin-registration.conf
          - name: waltid-enterprise-api-config
            mountPath: /config/enterprise.conf
            readOnly: true
            subPath: enterprise.conf
          - name: waltid-enterprise-api-config
            mountPath: /config/web.conf
            readOnly: true
            subPath: web.conf
          {{- if .Values.loggingConf }}
          - name: waltid-enterprise-api-config
            mountPath: /config/klogging.json
            readOnly: true
            subPath: klogging.json
          {{- end }}
      volumes:
        - name: waltid-enterprise-api-config
          configMap:
            name: {{ include "enterprise-stack.fullname" . }}-api-config
