apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "enterprise-stack.fullname" . }}-ingress
  labels:
  {{- include "enterprise-stack.labels" . | nindent 4 }}
  annotations:
  {{- if .Values.ingress.annotations }}
    {{- .Values.ingress.annotations | toYaml | nindent 4 }}
  {{- end }}
  {{- if .Values.ingress.clusterIssuer }}
    cert-manager.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.ingressClassName }}
  {{- if .Values.ingress.tls }}
  tls: 
    {{- .Values.ingress.tls | toYaml | nindent 4 }}
  {{- end }}
  rules:
  - host: {{ quote .Values.ingress.host }}
    http:
      paths:
      - path: /auth/
        pathType: Prefix
        backend:
          service:
            name: '{{ include "enterprise-stack.fullname" . }}-api-service'
            port:
              name: http
      - path: /v1/
        pathType: Prefix
        backend:
          service:
            name: '{{ include "enterprise-stack.fullname" . }}-api-service'
            port:
              name: http
      - path: /.well-known/
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ include "enterprise-stack.fullname" . }}-api-service'
            port:
              name: http
      - path: /swagger
        pathType: Prefix
        backend:
          service:
            name: '{{ include "enterprise-stack.fullname" . }}-api-service'
            port:
              name: http
      - path: /api.json
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ include "enterprise-stack.fullname" . }}-api-service'
            port:
              name: http
      - path: /livez
        pathType: Prefix
        backend:
          service:
            name: '{{ include "enterprise-stack.fullname" . }}-api-service'
            port:
              name: http
      - path: /features/
        pathType: Prefix
        backend:
          service:
            name: '{{ include "enterprise-stack.fullname" . }}-api-service'
            port:
              name: http
      - path: /debug/
        pathType: Prefix
        backend:
          service:
            name: '{{ include "enterprise-stack.fullname" . }}-api-service'
            port:
              name: http
      - path: /
        pathType: Prefix
        backend:
          service:
            name: '{{ include "enterprise-stack.fullname" . }}-ui-service'
            port:
              name: http
  - host: {{ quote (printf "*.%s" .Values.ingress.host) }}
    http:
      paths:
      - path: /auth/
        pathType: Prefix
        backend:
          service:
            name: '{{ include "enterprise-stack.fullname" . }}-api-service'
            port:
              name: http
      - path: /v1/
        pathType: Prefix
        backend:
          service:
            name: '{{ include "enterprise-stack.fullname" . }}-api-service'
            port:
              name: http
      - path: /.well-known/
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ include "enterprise-stack.fullname" . }}-api-service'
            port:
              name: http
      - path: /swagger
        pathType: Prefix
        backend:
          service:
            name: '{{ include "enterprise-stack.fullname" . }}-api-service'
            port:
              name: http
      - path: /api.json
        pathType: ImplementationSpecific
        backend:
          service:
            name: '{{ include "enterprise-stack.fullname" . }}-api-service'
            port:
              name: http
      - path: /livez
        pathType: Prefix
        backend:
          service:
            name: '{{ include "enterprise-stack.fullname" . }}-api-service'
            port:
              name: http
      - path: /features/
        pathType: Prefix
        backend:
          service:
            name: '{{ include "enterprise-stack.fullname" . }}-api-service'
            port:
              name: http
      - path: /debug/
        pathType: Prefix
        backend:
          service:
            name: '{{ include "enterprise-stack.fullname" . }}-api-service'
            port:
              name: http
      - path: /
        pathType: Prefix
        backend:
          service:
            name: '{{ include "enterprise-stack.fullname" . }}-ui-service'
            port:
              name: http